-- phpMyAdmin SQL Dump
-- version 4.8.4
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 04-01-2020 a las 22:38:44
-- Versión del servidor: 10.1.37-MariaDB
-- Versión de PHP: 7.3.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `peliculas`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `películas`
--

CREATE TABLE `películas` (
  `id` int(10) NOT NULL,
  `titulo` varchar(200) COLLATE utf8_spanish_ci NOT NULL,
  `país` varchar(50) COLLATE utf8_spanish_ci NOT NULL,
  `director` varchar(100) COLLATE utf8_spanish_ci NOT NULL,
  `género` varchar(100) COLLATE utf8_spanish_ci NOT NULL,
  `valoración` double NOT NULL,
  `premios` text COLLATE utf8_spanish_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

--
-- Volcado de datos para la tabla `películas`
--

INSERT INTO `películas` (`id`, `titulo`, `país`, `director`, `género`, `valoración`, `premios`) VALUES
(1, 'El padrino', 'Estados Unidos', 'Francis Ford Coppola', 'Drama', 9, '1972: 3 Oscars: Mejor película, Actor (Marlon Brando), Guión adaptado. 11[10*] nom.\r\n1972: 5 Globos de Oro: Película (Drama), Director, Actor (Brando), Guión y BSO\r\n1972: Premios BAFTA: Mejor música. 5 nominaciones, incluyendo Mejor actor (Brando)\r\n1972: Círculo de Críticos de Nueva York: Mejor actor secundario (Duvall). 4 nominaciones\r\n1972: National Board of Review: Mejor actor sec. (Pacino) y Mejores 10 films del año\r\n1972: Sindicato de Directores (DGA): Mejor director\r\n1972: Sindicato de Guionistas (WGA): Mejor guión adaptado drama\r\n1972: Premios David di Donatello: Mejor film extranjero y Premio Especial (Al Pacino)'),
(2, 'El Padrino. Parte II', 'Estados Unidos', 'Francis Ford Coppola', 'Drama', 8.9, '1974: 6 Oscars, incluyendo Película, Director, Actor de reparto (De Niro). 11 nom.\r\n1974: Globos de Oro: 6 nominaciones, incluyendo Mejor película - Drama\r\n1974: Círculo de Críticos de Nueva York: 4 nominaciones, incluyendo Mejor película\r\n1974: Sindicato de Directores (DGA): Mejor director\r\n1974: Sindicato de Guionistas (WGA): Mejor guión adaptado drama\r\n1975: Premios BAFTA: Mejor actor (Al Pacino). 4 nominaciones'),
(3, 'La lista de Schindler', 'Estados Unidos', 'Steven Spielberg', 'Drama', 8.6, '1993: 7 Oscars incluyendo mejor película y director. 12 nominaciones\r\n1993: 3 Globos de Oro: Película: drama, guión, director. 6 nominaciones\r\n1993: 7 Premios BAFTA, incluyendo mejor película y director. 13 nom.\r\n1993: National Board of Review: Mejor película. Mejores 10 películas del año\r\n1993: Círculo de Críticos de Nueva York: Mejor película, actor sec. y fotografía\r\n1993: Asociación de Críticos de Los Angeles: Mejor película, fotografía y diseño de prod.\r\n1993: Asociación de Críticos de Chicago: 6 premios, incl. Mejor película. 7 nom.\r\n1993: Sindicato de Productores (PGA): Mejor película\r\n1993: Sindicato de Directores (DGA): Mejor director\r\n1993: Sindicato de Guionistas (WGA): Mejor guión adaptado\r\n1994: Premios Cesar: Nominada a la Mejor película extranjera\r\n1994: Premios David de Donatello: Nominada a mejor película extranjera'),
(4, 'Cadena perpetua', 'Estados Unidos', 'Frank Darabont', 'Drama', 8.6, '1994: Oscar: 7 nominaciones, incluyendo mejor película y actor (Freeman)\r\n1994: Globo de Oro: 2 nominaciones: mejor actor drama (Freeman) y guión\r\n1994: Sindicato de Productores (PGA): Nominada a Mejor película\r\n1994: Sindicato de Directores (DGA): Nominada a Mejor director\r\n1994: Sindicato de Guionistas (WGA): Nominada a Mejor guión adaptado\r\n1994: Sindicato de Actores (SAG): 2 nom. Mejor actor (Freeman y Robbins)\r\n1994: Asociación de Críticos de Chicago: 3 nominaciones, incluyendo Mejor película'),
(5, 'Pulp Fiction', 'Estados Unidos', 'Quentin Tarantino', 'Thriller', 8.6, '1994: Oscar: Mejor guión original. 7 nominaciones, incluyendo Mejor película\r\n1994: Globo de Oro: Mejor guión. 6 nominaciones\r\n1994: Festival de Cannes: Palma de Oro\r\n1994: 2 Premios BAFTA: Mejor actor sec. (Samuel L. Jackson) y guión. 9 nom.\r\n1994: Premios Cesar: Nominada a Mejor película extranjera\r\n1994: Premios David di Donatello: Mejor film y actor extranjero (Travolta). 3 nom.\r\n1994: National Board of Review: Mejor película (ex-aequo)\r\n1994: Círculo de Críticos de Nueva York: Mejor director y guión. 5 nom.\r\n1994: Asociación de Críticos de Los Angeles: Mejor película, dirección, actor y guion\r\n1994: Premios Independent Spirit: Mejor película, director, actor y guión. 6 nominaciones\r\n1994: Sindicato de Productores (PGA): Nominada a Mejor película\r\n1994: Sindicato de Directores (DGA): Nominada a Mejor director\r\n1994: Sindicato de Actores (SAG): Nom. a Mejor actor (Travolta), actor sec. (Jackson) y actriz sec. (Thurman)\r\n1994: Asociación de Críticos de Chicago: Mejor director y guión. 6 nominaciones'),
(6, 'El golpe', 'Estados Unidos', 'George Roy Hill', 'Intriga', 8.6, '1973: Oscars: 7 premios, incluyendo mejor película, director y guión. 10 nom.\r\n1973: Globos de Oro: Nominada a mejor guión\r\n1973: National Board of Review: Mejor película\r\n1973: Sindicato de Directores (DGA): Mejor director\r\n1973: Sindicato de Guionistas (WGA): Nominada a Mejor guión original drama\r\n1973: Premios David di Donatello: Mejor actor extranjero (Robert Redford)'),
(7, 'La vida es bella', 'Italia', 'Roberto Benigni', 'Drama', 8.5, '1998: 3 Oscars: Mejor actor (Benigni), película habla no inglesa, bso. 7 nominaciones\r\n1998: Festival de Cannes: Gran Premio Especial del Jurado. 2 nominaciones\r\n1998: Premios BAFTA: Mejor actor (Benigni). 3 nominaciones\r\n1998: Premios Cesar: Mejor película extranjera\r\n1998: Premios Goya: Mejor película europea\r\n1998: National Board of Review: Premio especial (Roberto Benigni)\r\n1998: Premios del Cine Europeo: Mejor película y actor (Roberto Benigni)\r\n1998: Festival de Toronto: Premio del Público a Mejor película, Premio a Benigni\r\n1998: Festival de Montreal: Premio del Público\r\n1998: Critics\' Choice Awards: Mejor película de habla no inglesa. 2 nominaciones\r\n1997: Premios David di Donatello: 8 premios, incluyendo mejor película. 12 nom.\r\n1998: Sindicato de Productores (PGA): Nominada a Mejor película\r\n1998: Sindicato de Directores (DGA): Nominada a Mejor director\r\n1998: Sindicato de Actores (SAG): Mejor actor (Roberto Benigni). 2 nominaciones\r\n1998: Asociación de Críticos de Chicago: Mejor película extranjera. 3 nominaciones\r\n1999: British Independent Film Awards (BIFA): Nom. Mejor película lengua no inglesa'),
(8, 'Ciudad de dios', 'Brasil', 'Fernando Meireles', 'Drama', 8.4, '2003: 4 nominaciones al Oscar: Mejor director, fotografía, montaje, guión adaptado\r\n2002: Globos de oro: Nominada Mejor película de habla no inglesa\r\n2002: Premios BAFTA: Mejor montaje. Nominada a mejor película de habla no inglesa\r\n2003: Círculo de Críticos de Nueva York: Mejor película extranjera\r\nAsociación de Críticos de Los Angeles: Nominada a Mejor película extranjera\r\n2003: Festival de Toronto: Mejor película extranjera\r\n2003: Critics\' Choice Awards: Nominada a mejor película de habla no inglesa\r\n2003: Asociación de Críticos de Chicago: Mejor película extranjera\r\n2003: Premios Independent Spirit: Nominada a Mejor película extranjera\r\n2003: British Independent Film Awards (BIFA): Mejor película internacional independiente'),
(9, 'Uno de los nuestros', 'Estados Unidos', 'Martin Scorsese', 'Drama', 8.4, '1990: Oscar: Mejor actor secundario (Joe Pesci). 6 nominaciones\r\n1990: Globos de Oro: 5 nom., incluyendo Drama, Director y Actor Sec. (Pesci)\r\n1990: 5 Premios BAFTA: Incluyendo mejor película y director. 7 nominaciones\r\n1990: Festival de Venecia: León de Plata (Mejor director)\r\n1990: National Board of Review: Mejor Actor Sec. (Pesci), 10 mejores películas\r\n1990: Círculo de Críticos de Nueva York: Mejor película, director y actor. 6 nom.\r\n1990: Asociación de Críticos de Los Angeles: 5 premios incl. Mejor película y director\r\n1990: Premios César: Nominada a Mejor película extranjera\r\n1990: Asociación Críticos de Boston: Mejor Película, Director, Actor Sec. (Pesci)\r\n1990: David di Donatello: Nominada Película Extranjera, Actor Extranjero (De Niro)\r\n1990: Asociación de Críticos de Chicago: 5 premios incl. Mejor película y director. 7 nom.\r\n1990: Sindicato de Productores (PGA): Nominada a Mejor película\r\n1990: Sindicato de Directores (DGA): Nominada a Mejor director\r\n1990: Sindicato de Guionistas (WGA): Nom. a Mejor guión adaptado'),
(10, 'Alguien voló sobre el nido del cuco', 'Estados Unidos', 'Milos Forman', 'Drama', 8.4, '1975: 5 Oscars: Película, director, actor (Nicholson), actriz (Fletcher), guión adaptado\r\n1975: 5 Globos de Oro: Película, director, actor (Nicholson), actriz (Fletcher), guión\r\n1976: Premios BAFTA: 6 Premios incluyendo mejor película, director y actor. 10 nom.\r\n1975: Círculo de Críticos de Nueva York: Mejor actor (Nicholson). 2 nominaciones\r\n1975: Asociación de Críticos de Los Angeles: Mejor película\r\n1975: Sindicato de Directores (DGA): Mejor director\r\n1975: Sindicato de Guionistas (WGA): Mejor guión adaptado drama\r\n1975: Premios David di Donatello: Mejor director y actor extranjero (Nicholson)\r\n1976: Premios César: Nominada a Mejor Película Extranjera'),
(11, 'American History X', 'Estados Unidos', 'Tony Kaye', 'Drama', 8.3, '1998: Nominada al Oscar: Mejor actor (Edward Norton)\r\n1998: Asociación de Críticos de Chicago: Nominada a Mejor actor (Edward Norton)'),
(12, 'Dersu Uzala (El cazador)', 'URSS', 'Akira Kurosawa', 'Aventuras', 8.3, '1975: Oscar: Mejor película de habla no inglesa\r\n1975: Gran premio en el festival internacional de Moscú\r\n1976: Premios David di Donatello: Mejor director extranjero'),
(13, 'Cinema Paradiso', 'Italia', 'Giuseppe Tornatore', 'Drama', 8.3, '1989: Premios Oscar: Mejor película de habla no inglesa\r\n1989: Globo de Oro: Mejor película de habla no inglesa\r\n1990: 5 Premios BAFTA, incluyendo mejor película de habla no inglesa. 11 nom.\r\n1990: Círculo de Críticos de Nueva York: Nominada a Mejor película extranjera\r\n1989: Festival de Cannes: Premio Especial del Jurado\r\n1989: Premios César: Mejor póster. Nominada a Mejor Película Extranjera\r\n1989: Premios del Cine Europeo: Mejor actor (Philippe Noiret)\r\n1988: Premios David di Donatello: Mejor música. 5 nominaciones\r\n1990: Sindicato de Directores (DGA): Nominada a Mejor director'),
(14, 'Érase una vez en América', 'Estados Unidos', 'Sergio Leone', 'Drama', 8.3, '1985: 2 nominaciones a los Globos de Oro: Mejor director, banda sonora original\r\n1984: 2 premios BAFTA: Mejor vestuario, banda sonora original. 5 nominaciones\r\n1984: Premios David di Donatello: Nominada a Mejor Director Extranjero\r\n1984: Asociación de Críticos de Los Angeles: Mejor banda sonora. 3 nominaciones\r\n1985: Premios de la Academia Japonesa: Mejor Película Extranjera\r\n1985: Sindicato Italiano de Periodistas de Cine: 5 premios incluyendo Mejor Director\r\n1985: Kinema Junpo Awards (Japón): Mejor Película Extranjera\r\n1985: Premios Sant Jordi: Mejor Actor Extranjero (Robert de Niro)'),
(15, 'Seven', 'Estados Unidos', 'David Fincher', 'Thriller', 8.2, '1995: Nominada al Oscar: Mejor montaje\r\n1995: Nominada Premios BAFTA: Mejor guión original\r\n1995: National Board of Review: Mejor actor de reparto (Kevin Spacey)\r\n1995: Círculo de Críticos de Nueva York: Mejor actor secundario (Kevin Spacey)\r\n1995: Asociación de Críticos de Los Angeles: 3 nom. incluyendo Mejor fotografía\r\n1995: Asociación de Críticos de Chicago: Mejor fotografía. 3 nominaciones\r\n1995: Sindicato de Productores (PGA): Nominada a Mejor película'),
(16, 'El pianista', 'Reino Unido', 'Roman Polanski', 'Drama', 8.2, '2002: 3 Oscar: Mejor director, actor (Adrien Brody), guión adaptado. 7 nominaciones\r\n2002: Globos de Oro: 2 nominaciones: Mejor película y actor drama (Adrien Brody)\r\n2002: Festival de Cannes: Palma de Oro\r\n2002: 2 premios BAFTA: Mejor película y director. 7 nominaciones\r\n2002: 7 premios Cesar incluyendo mejor película, actor, director. 10 nominaciones\r\n2002: Premios David de Donatello: Mejor película extranjera\r\n2002: Premios Goya: Mejor película europea\r\n2002: Premios del Cine Europeo: Mejor fotografía. 4 nominaciones\r\n2002: Critics\' Choice Awards: Nominada a mejor película y mejor director\r\n2002: Sindicato de Directores (DGA): Nominada a Mejor director\r\n2002: Sindicato de Actores (SAG): Nominado a Mejor actor (Adrien Brody)\r\n2002: Asociación de Críticos de Chicago: 3 nom., incl. Mejor película y director'),
(17, 'Apocalypse Now', 'Estados Unidos', 'Francis Ford Coppola', 'Bélico', 8.2, '1979: 2 Oscars: Mejor fotografía y sonido. 8 nominaciones\r\n1979: 3 Globos de Oro: Director, Actor Sec. (Duvall), Banda Sonora. 4 nom.\r\n1979: Premios BAFTA: Mejor director y actor secundario (Duvall). 9 nominaciones\r\n1979: Sindicato de Directores (DGA): Nominada a Mejor director\r\n1979: Sindicato de Guionistas (WGA): Nominada a Mejor guión original drama\r\n1979: Festival de Cannes: Palma de Oro (ex aequo con \"El tambor de Hojalata\")\r\n1979: Premios César: Nominada a Mejor película extranjera\r\n1979: Premios David di Donatello: Mejor director extranjero'),
(18, 'Sin perdón', 'Estados Unidos', 'Clint Eastwood', 'Western', 8.2, '1992: 4 Oscar: Mejor película, director, actor sec. (Hackman), montaje. 10 nominaciones\r\n1992: 2 Globos de Oro: Mejor director (Eastwood), actor sec. (Hackman). 4 nominaciones\r\n1992: BAFTA: Mejor actor sec. (Hackman). 6 nominaciones, incluyendo mejor película\r\n1992: Círculo de Críticos de Nueva York: Mejor actor sec. (Hackman). 4 nominaciones\r\n1992: Sindicato de Directores (DGA): Mejor director\r\n1992: Editores de Cine Americanos: Mejor Montaje (Joel Cox)\r\n1992: Sociedad de Críticos de Boston: Mejor Película, Actor sec. (Hackman), fotografía\r\n1992: Asociación Críticos de Chicago: 5 nom., incl. Mejor película y Mejor director\r\n1992: Gremio de Directores de América: Mejor Director\r\n1992: Fotogramas de Plata: Mejor Película Extranjera\r\n1992: Círculo de Críticos de Kansas: Mejor Película, Director y Actor sec. (Hackman)\r\n1992: Círculo de Críticos de Londres: Mejor Película del año\r\n1992: Asociación de Críticos de Los Angeles: 5 premios incluyendo Mejor película\r\n1992: National Board of Review: 10 mejores películas del año\r\n1992: Sociedad Nacional de Críticos de Cine: 4 premios incluyendo Mejor Película\r\n1992: Gremio de Guionistas de América: Nominado a Mejor Guión Original\r\n1992: Sindicato de Productores (PGA): Nominada a Mejor película\r\n1992: Sindicato de Guionistas (WGA): Nominada a Mejor guión original\r\n1993: Premios de la Academia Japonesa: Nominada a Mejor Película Extranjera'),
(19, 'El precio del poder', 'Estados Unidos', 'Brian De Palma', 'Drama', 8.2, '1983: Globos de Oro: Nom. Mejor actor (Pacino), actor sec. (Bauer) y banda sonora\r\n1983: Nominada a los Premios Razzie: Peor director'),
(20, 'El silencio de los corderos', 'Estados Unidos', 'Jonathan Demme', 'Thriller', 8.2, '1991: 5 Oscars: Película, director, actor (Hopkins), actriz (Foster), guión adaptado.\r\n1991: Globos de Oro: Mejor actriz drama (Foster). 5 nominaciones\r\n1991: 2 Premios BAFTA: Mejor actor (Hopkins) y actriz (Foster). 9 nominaciones\r\n1991: Festival de Berlín: Oso de Plata - Mejor director (ex aequo \"Ultrà\")\r\n1991: Nominada al Cesar: Mejor película extranjera\r\n1991: 3 premios National Board of Review: Director, película, actor sec. (Hopkins)\r\n1991: Círculo de Críticos de Nueva York: 4 premios incluyendo mejor película\r\n1991: Asociación de Críticos de Los Angeles: Nominada a Mejor banda sonora\r\n1991: Asociación de Críticos de Chicago: 5 premios, incluyendo Mejor película\r\n1991: Sindicato de Productores (PGA): Mejor película\r\n1991: Sindicato de Directores (DGA): Mejor director\r\n1991: Sindicato de Guionistas (WGA): Mejor guión adaptado'),
(21, 'La huella', 'Reino Unido', 'Joseph L. Mankiewicz', 'Intriga', 8.2, '1972: Oscar: 4 nominaciones, director, actores (L. Olivier y M. Caine) y BSO\r\n1972: Globos de Oro: 3 nominaciones, incluyendo mejor película - Drama\r\n1972: Círculo de Críticos de Nueva York: Mejor actor (Laurence Olivier)\r\n1972: Premios David di Donatello: Mejor actor extranjero (Laurence Olivier)\r\n1973: Premios BAFTA: 4 nominaciones, incluyendo Mejor actor (Oliver) y guión'),
(22, 'La naranja mecánica', 'Reino Unido', 'Stanley Kubrick', 'Drama', 8.2, '1971: 4 nominaciones al Oscar: Mejor película, director, montaje, guión adaptado\r\n1971: Globos de Oro: 3 nominaciones, incluyendo mejor película - Drama\r\n1971: Círculo de Críticos de Nueva York: Mejor película y director. 3 nominaciones\r\n1971: Sindicato de Directores (DGA): Nominada a Mejor director\r\n1971: Sindicato de Guionistas (WGA): Nominada a Mejor guión adaptado drama\r\n1972: Premios BAFTA: 7 nominaciones, incluyendo Mejor película y mejor director'),
(23, 'Forrest Gump', 'Estados Unidos', 'Robert Zemeckis', 'Drama', 8.2, '1994: 6 Oscars: incluyendo película, director, actor (Tom Hanks). 13 nom.\r\n1994: 3 Globos de Oro: Película: Drama, director, actor drama (Hanks). 7 nom.\r\n1994: BAFTA: Mejores efectos visuales. 8 nominaciones, inc. mejor película\r\n1994: 3 Premios National Board of Review: Mejor película, actor, actor de reparto (Sinise)\r\n1994: Sindicato de Productores (PGA): Mejor película\r\n1994: Sindicato de Directores (DGA): Mejor director\r\n1994: Sindicato de Guionistas (WGA): Mejor guión adaptado\r\n1994: Sindicato de Actores (SAG): Mejor actor (Tom Hanks). 4 nominaciones\r\n1994: Asociación de Críticos de Chicago: Mejor actor (Tom Hanks). 5 nominaciones'),
(24, 'Joker', 'Estados Unidos', 'Todd Phillips', 'Thriller', 8.2, '2019: Globos de Oro: Nom. a mejor película drama, director, actor (Phoenix) y bso\r\n2019: Festival de Venecia: León de Oro (Mejor película)\r\n2019: American Film Institute (AFI): Top 10 - Mejores películas del año\r\n2019: Critics Choice Awards: 7 nominaciones incluy. mejor película y actor (Phoenix)\r\n2019: Asociación de Críticos de Chicago: Nominada a Mejor actor (Joaquin Phoenix)\r\n2019: Satellite Awards: Mejor guion adaptado y música. 10 nominaciones\r\n2019: Sindicato de Actores (SAG): Nominada a mejor actor y especialistas de acción'),
(25, 'Gran Torino', 'Estados Unidos', 'Clint Eastwood', 'Drama', 8.2, '2009: Premios César: Mejor película extranjera\r\n2008: Globos de Oro: Nominada a la Mejor canción\r\n2008: Círculo de Críticos de Nueva York: Nominada a Mejor actor (Clint Eastwood)\r\n2008: National Board of Review: Mejor actor (Clint Eastwood), mejor guión original\r\n2008: Premios David di Donatello: Mejor film extranjero\r\n2008: American Film Institute (AFI): Top 10 - Mejores películas del año\r\n2008: Critics\' Choice Awards: Nominado Mejor actor (Clint Eastwood)\r\n2008: Asociación de Críticos de Chicago: Nominada a mejor actor (Clint Eastwood).\r\n2009: Premios Sur: Nominada a mejor película extranjera'),
(27, 'La vida de Brian', 'Reino Unido', 'Terry Jones', 'Comedia', 7.9, '-'),
(28, 'Amanece, que no es poco', 'España', 'José Luis Cuerda', 'Comedia', 7.5, '1989: Premios Goya: 3 nominaciones'),
(29, 'Los caballeros de la mesa cuadrada y sus locos seguidores', 'Reino Unido', 'Terry Jones', 'Comedia', 7.4, '1976: Premios Hugo: Nominada a Mejor Representación Dramática'),
(30, 'Reservoir Dogs', 'Estados Unidos', 'Quentin Tarantino', 'Thriller', 8.1, '1992: Sitges: Mejor director, mejor guión\r\n1992: Festival de Toronto: Premio FIPRESCI\r\n1992: Premios Independent Spirit: Mejor actor secundario (Buscemi). 3 nominaciones\r\n1992: Círculo de Críticos de Nueva York: Nominada Mejor director novel y actor (Keitel)\r\n1992: Asociación de Críticos de Chicago: Nominada a Mejor película y Mejor director'),
(31, 'El caballero oscuro', 'Estados Unidos', 'Christopher Nolan', 'Acción', 8.1, '2008: 2 Oscar: Mejor actor sec. (H. Ledger) y montaje sonido. 8 nominaciones\r\n2008: Globo de Oro: Mejor actor secundario (Heath Ledger)\r\n2008: Premios BAFTA: Mejor actor secundario (Heath Ledger). 9 nominaciones\r\n2008: Festival de Toronto: Mejor actor secundario (Heath Ledger)\r\n2008: Círculo de Críticos de Nueva York: Nominada Mejor actor sec. (Ledger) y fotografía\r\n2008: Premios Goya: Nominada a la mejor Película Europea\r\n2008: Asociación de Críticos de Los Angeles: Mejor actor secundario (H. Ledger)\r\n2008: Saturn Awards: 5 premios incluyendo Mejor Película de Acción. 11 nom.\r\n2008: Art Directors Guild: Mejor Diseño de producción en película fantástica\r\n2008: Broadcast Film Critics Association: Mejor Película Acción, Actor Sec. 6 nom.\r\n2008: National Board of Review: Top Ten Films\r\n2008: American Film Institute (AFI): Top 10 - Mejores películas del año\r\n2008: 2 Critics\' Choice Awards: Mejor película de acción, actor secundario. 6 nom.\r\n2008: Asociación de Críticos de Chicago: Mejor actor sec. (Ledger). 6 nominaciones\r\n2008: Sindicato de Productores (PGA): Nominada a Mejor película\r\n2008: Sindicato de Directores (DGA): Nominada a Mejor director\r\n2008: Sindicato de Guionistas (WGA): Nominada a Mejor guión adaptado\r\n2008: Sindicato de Actores (SAG): Mejor actor sec. (Ledger) y especialistas de acción'),
(32, 'Gladiator', 'Estados Unidos', 'Ridley Scott', 'Acción', 7.9, '2000: 5 Oscars: Película, actor (Crowe), vestuario, sonido, efectos visuales. 12 nom.\r\n2000: 2 Globos de Oro: Mejor película drama y BSO. 5 nominaciones, incl. Director.\r\n2000: 4 Premios BAFTA: Mejor película, fotografía, montaje y diseño prod. 14 nom.\r\n2000: 2 premios National Board of Review: Mejor diseño de producción y actor sec.\r\n2000: American Film Institute (AFI): Top 10 - Mejores películas del año\r\n2000: 6 Critics\' Choice Awards: Incluyendo mejor película, actor, actor sec. y fot.\r\n2000: Sindicato de Productores (PGA): Mejor película\r\n2000: Sindicato de Directores (DGA): Nominada a Mejor director\r\n2000: Sindicato de Actores (SAG): 3 nominaciones, incl. Mejor reparto\r\n2000: Asociación de Críticos de Chicago: Nom. a Mejor fotografía y banda sonora'),
(33, 'Mystic River', 'Estados Unidos', 'Clint Eastwood', 'Intriga', 8, '2003: 2 premios Oscar: Mejor actor (Penn), actor sec. (Robbins). 6 nominaciones\r\n2003: 2 Globos de Oro: Mejor actor (Penn), actor sec. (Robbins). 5 nominaciones\r\n2003: BAFTA: 4 nominaciones, Mejor actor, actor sec., actriz sec. y guión adaptado\r\n2003: Festival de Cannes: Premio Golden Coach (Eastwood). 2 nominaciones\r\n2003: Premios Cesar: Mejor película extranjera\r\n2003: Nominada al David de Donatello: Mejor película extranjera\r\n2003: 2 premios National Board of Review: Mejor actor (Sean Penn), película\r\n2003: American Film Institute (AFI): Top 10 - Mejores películas del año\r\n2003: Círculo de Críticos de Nueva York: Nominada mejor película y mejor actor (Penn)\r\n2003: Asociación de Críticos de Los Angeles: Nominada a Mejor dirección y actor\r\n2003: 2 Critics\' Choice Awards: Mejor actor (Penn) y secundario (Robbins). 8 nom.\r\n2003: Asociación de Críticos de Chicago: Mejor actor secundario (Robbins). 6 nom.\r\n2003: Sindicato de Productores (PGA): Nominada a Mejor película\r\n2003: Sindicato de Directores (DGA): Nominada a Mejor director\r\n2003: Sindicato de Guionistas (WGA): Nominada a Mejor guión adaptado\r\n2003: Sindicato de Actores (SAG): Mejor actor secundario (Robbins). 3 Nom.'),
(34, 'Sospechosos habituales', 'Estados Unidos', 'Bryan Singer', 'Intriga', 8, '1995: 2 Oscars: Mejor guión original, actor secundario (Spacey)\r\n1995: Globo de Oro: Nominada a Mejor actor secundario (Spacey)\r\n1995: 2 premios BAFTA: Mejor montaje y guión original. Nominada mejor película\r\n1995: Premios Cesar: Nominada a mejor película extranjera\r\n1995: 2 premios National Board of Review: Mejor reparto, actor sec. (Spacey)\r\n1995: Círculo de Críticos de Nueva York: Mejor actor secundario (Spacey)\r\n1995: Asociación de Críticos de Los Angeles: Nominada a Mejor actor sec. (Spacey)\r\n1995: Critics\' Choice Awards: Mejor actor secundario (ex-aequo) (Kevin Spacey)\r\n1995: Premios Independent Spirit: Mejor actor sec. (Del Toro) y Mejor guión. 3 nominaciones\r\n1995: Sindicato de Productores (PGA): Nominada a Mejor película\r\n1995: Sindicato de Actores (SAG): Nominada a Mejor actor secundario (Spacey)\r\n1995: Asociación de Críticos de Chicago: Mejor actor sec. (Spacey) y mejor guión. 3 nom.'),
(35, 'La chaqueta metálica', 'Reino Unido', 'Stanley Kubrick', 'Bélico', 8.2, '1987: Nominada al Oscar: mejor guión adaptado\r\n1987: Globos de Oro: Nominado a Mejor actor de reparto (R. Lee Ermey)\r\n1987: Premios BAFTA: Nominada Mejores efectos especiales y sonido\r\n1987: Sociedad de Críticos de Boston: Mejor actor de reparto (R. Lee Ermey)\r\n1987: Círculo de Críticos de Nueva York: 2 nominaciones incl. Mejor actor sec. (D\'Onofrio)\r\n1987: Sindicato de Guionistas (WGA): Nominada a Mejor guión adaptado\r\n1987: Premios David di Donatello: Mejor productor extranjero. 2 nominaciones'),
(36, 'Salvar al soldado Ryan', 'Estados Unidos', 'Steven Spielberg', 'Bélico', 7.8, '1998: 5 Oscars: Director, fotografía, montaje, sonido, efectos sonoros. 11 nom.\r\n1998: 2 Globos de Oro: Mejor película: Drama, director. 5 nominaciones\r\n1998: 2 premios BAFTA: Mejores efectos visuales y sonido. 10 nom.\r\n1998: Nominada al Cesar: Mejor película extranjera\r\n1998: Círculo de Críticos de Nueva York: Mejor película. 2 nominaciones\r\n1998: Asociación de Críticos de Los Angeles: Mejor película, dirección y fotografía\r\n1998: 3 Critics\' Choice Awards: Mejor película, director y banda sonora\r\n1998: Asociación de Críticos de Chicago: Mejor película. 4 nominaciones\r\n1998: Sindicato de Productores (PGA): Mejor película\r\n1998: Sindicato de Directores (DGA): Mejor director\r\n1998: Sindicato de Guionistas (WGA): Nominada a Mejor guión original\r\n1998: Sindicato de Actores (SAG): Nom. Mejor reparto (Largometraje) y actor (Hanks)'),
(37, 'Doce hombres sin piedad', 'Estados Unidos', 'Sidney Lumet', 'Drama', 8.7, '1957: 3 nominaciones al Oscar: Mejor película, director, guión adaptado\r\n1957: Globos de Oro: 4 nom., incluyendo mejor película drama, director y actor\r\n1957: Premios BAFTA: mejor actor extranjero (Fonda). Nominada mejor película\r\n1957: Sindicato de Directores (DGA): Nominada a Mejor director\r\n1957: Sindicato de Guionistas (WGA): Mejor guión drama\r\n1957: Festival de Berlín: Oso de Oro, Premio OCIC\r\n1957: Círculo de Críticos de Nueva York: Nominada a Mejor película y Mejor director\r\n1957: National Board of Review: Top 10 Mejores películas del año'),
(38, 'Origen', 'Estados Unidos', 'Christopher Nolan', 'Intriga', 8, '2010: 4 Oscars: mejor fotografía, sonido, ef. sonoros y visuales. 8 nominaciones\r\n2010: Globos de Oro: 4 nominaciones: mejor película drama, director, guión, BSO\r\n2010: 3 Premios BAFTA técnicos. 9 nominaciones, incluyendo mejor película y director\r\n2010: Satellite Awards: Mejor fotografía, dirección artística, BSO. 11 nominaciones\r\n2010: Asociación de Críticos de los Angeles: Mejor diseño de producción\r\n2010: American Film Institute (AFI): Top 10 - Mejores películas del año\r\n2010: 6 Critics\' Choice Awards, incluyendo mejor película de acción. 10 nominaciones\r\n2010: Asociación de Críticos de Chicago: Mejor Guión y Mejor Fotografía. 5 nominaciones\r\n2010: Sindicato de Productores (PGA): Nominada a Mejor película\r\n2010: Sindicato de Directores (DGA): Nominada a Mejor director\r\n2010: Sindicato de Guionistas (WGA): Mejor guión original\r\n2010: Sindicato de Actores (SAG): Mejores especialistas de acción (Largometraje)\r\n2010: Premios Gaudí: Nominada a Mejor película europea'),
(39, 'Intocable', 'Francia', 'Olivier Nakache, Eric Toledano', 'Drama', 8, '2012: Globos de Oro: nominada a mejor película de habla no inglesa\r\n2011: Premios Cesar: Mejor actor (Omar Sy). 9 nominaciones\r\n2012: Premios BAFTA: Nominada a Mejor película de habla no inglesa\r\n2012: Premios Goya: Mejor película europea\r\n2011: Festival de San Sebastián: Sección oficial no competitiva - Clausura\r\n2011: Festival de Tokyo: Mejor película, Mejor actor (François Cluzet & Omar Sy)\r\n2011: Premios David di Donatello: Nominada a Mejor película de la Unión Europea\r\n2012: Premios del Cine Europeo: 4 nominaciones, incluyendo Mejor película\r\n2012: Satellite Awards: Mejor película extranjera (ex-aequo)\r\n2012: Asociación de Críticos de Chicago: Nominada a Mejor película extranjera\r\n2012: Premios Gaudí: Nominada a Mejor película europea'),
(40, 'Django desencadenado', 'Estados Unidos', 'Quentin Tarantino', 'Western', 7.9, '2012: 2 Oscars: mejor guión original y actor secundario (Waltz). 5 nominaciones\r\n2012: 2 Globos de Oro: Mejor guión y actor secundario (Waltz). 5 nominaciones\r\n2012: Critics Choice Awards: Mejor guión original. Nominada a mejor película\r\n2012: 2 Premios BAFTA: Mejor guión y actor secundario (Waltz). 5 nominaciones\r\n2012: Círculo de Críticos de Nueva York: Nominada a mejor actor secundario (Waltz)\r\n2012: National Board of Review (NBR): 10 mejores films y mejor actor sec. (Dicaprio)\r\n2012: Asociación de Críticos de Los Angeles: Nominada a Mejor actor sec. (Waltz)\r\n2012: American Film Institute: Top 10 - Mejores películas del año\r\n2012: Premios David di Donatello: Mejor película extranjera\r\n2012: Asociación de Críticos de Chicago: 2 nom. incluyendo mejor actor sec. (DiCaprio)\r\n2012: Sindicato de Productores (PGA): Nominada a Mejor película\r\n2013: Premios César: Nominada a Mejor película extranjera'),
(41, 'Interstellar', 'Estados Unidos', 'Christopher Nolan', 'Drama', 7.8, '2014: Oscar: Mejores efectos visuales. 5 nominaciones incl. mejor banda sonora\r\n2014: Globos de Oro: Nominada a Mejor banda sonora original\r\n2014: Premios BAFTA: Mejores efectos especiales visuales\r\n2014: American Film Institute (AFI): Top 10 - Mejores películas del año\r\n2014: Satellite Awards: 3 nominaciones incluyendo Mejor fotografía\r\n2014: Critics Choice Awards: Mejor película de ciencia ficción\r\n2014: Asociación de Críticos de Chicago: 4 nominaciones incluyendo Mejor director'),
(42, 'El irlandés', 'Estados Unidos', 'Martin Scorsese', 'Thriller', 7.6, '2019: Globos de Oro: 5 nominaciones incluyendo mejor película drama y director\r\n2019: Círculo de Críticos de Nueva York: Mejor película y actor secundario (Pesci)\r\n2019: National Board of Review (NBR): Mejor película y guion adaptado\r\n2019: American Film Institute (AFI): Top 10 - Mejores películas del año\r\n2019: Asociación de Críticos de Los Angeles: Nom. a mejor película, director y actor sec.\r\n2019: Critics Choice Awards: 14 nominaciones incluyendo mejor película y director\r\n2019: Asociación de Críticos de Chicago: Mejor montaje. 8 nominaciones\r\n2019: Satellite Awards: 6 nominaciones, inc. mejor guion adap. y actor sec. (Pesci)\r\n2019: Sindicato de Actores (SAG): 4 nominaciones incluyendo mejor reparto'),
(43, 'Shutter island', 'Estados Unidos', 'Martin Scorsese', 'Intriga', 7.6, '2010: National Board of Review: Top 10 mejores películas, mejor diseño prod.\r\n2010: Festival de Berlín: Sección oficial de largometrajes a concurso\r\n2010: Satellite Awards: Nominada Fotografía, Sonido, Montaje y Dirección Artística\r\n2010: Asociación de Críticos de Chicago: Nominada Mejor Fotografía\r\n2010: Saturn Awards: 5 nominaciones incluyendo Película Terror/Thriller\r\n2010: Sociedad de Editores de Sonido: Nominada a Mejor Sonido\r\n2010: Sociedad de Críticos de Las Vegas: Nominada Mejor Montaje\r\n2010: Sociedad de Críticos Online: Nominada Mejor Fotografía\r\n2010: Sociedad de Críticos de Phoenix: Nominada Mejor Película y Montaje\r\n2010: Sociedad de Críticos de San Diego: Mejor Diseño de Producción. 3 nom.\r\n2010: Sindicato Italiano de Periodistas de Cine: Nom. Mejor Director no europeo'),
(44, 'Cisne negro', 'Estados Unidos', 'Darren Aronofsky', 'Drama', 7.6, '2010: Premios Oscar: Mejor Actriz (Portman). 5 nominaciones, incl. Mejor película\r\n2010: Globo de Oro: Mejor Actriz (Portman). 4 nominaciones, incl. Mejor película\r\n2010: Premios BAFTA: Mejor Actriz (Portman). 12 nominaciones, incl. Mejor película\r\n2010: Círculo de Críticos de Nueva York: Mejor fotografía\r\n2010: Festival de Venecia: Mejor actriz o actor joven (Mila Kunis)\r\n2010: 4 Premios Independent Spirit: Mejor film, director, actriz (Portman) y fotografía\r\n2010: Satellite Awards: 5 nominaciones, incl. director y actriz principal (Portman)\r\n2010: Asociación de Críticos de Los Angeles: Mejor fotografía\r\n2010: American Film Institute (AFI): Top 10 - Mejores películas del año\r\n2011: Premios Cesar: Nominada a Mejor película extranjera\r\n2010: Critics\' Choice Awards: Mejor actriz. 12 nominaciones, incl. Mejor película\r\n2010: Asociación de Críticos de Chicago: Actriz (Portman) y Banda sonora. 6 nom.\r\n2010: Sindicato de Productores (PGA): Nominada a Mejor película\r\n2010: Sindicato de Directores (DGA): Nominada a Mejor director\r\n2010: Sindicato de Guionistas (WGA): Nominada a Mejor guión original\r\n2010: Sindicato de Actores (SAG): Mejor actriz (Portman). 3 nominaciones'),
(45, 'El lobo de Wall Street ', 'Estados Unidos', 'Martin Scorsese', 'Drama', 7.6, '2013: Premios Oscar: 5 nominaciones, incluyendo mejor película y director\r\n2013: Globos de Oro: Mejor actor de comedia (Dicaprio). Nomin. a mejor película\r\n2013: Premios BAFTA: 4 nominaciones, incluyendo Mejor director\r\n2013: Critics Choice: Mejor actor de comedia (Dicaprio). 6 nominaciones\r\n2013: National Board of Review (NBR): Top 10 y mejor guión adaptado\r\n2013: American Film Institute: Top 10 - Mejores películas del año\r\n2013: Satellite Awards: 5 nominaciones, incluyendo mejor película y director\r\n2013: Sindicato de Productores (PGA): Nominada a Mejor película\r\n2013: Sindicato de Directores (DGA): Nominada a Mejor director\r\n2013: Sindicato de Guionistas (WGA): Nominada a Mejor guión adaptado\r\n2013: Premios David di Donatello: Nominada a mejor film extranjero\r\n2013: Asociación de Críticos de Chicago: 2 nom. incluyendo Mejor guión adaptado'),
(46, '12 años de esclavitud', 'Estados Unidos', 'Steve McQueen', 'Drama', 7.3, '2013: 3 Premios Oscar: mejor película, guión y actriz secundaria. 9 nominaciones\r\n2013: Globos de Oro: Mejor película dramática. 7 nominaciones\r\n2013: Premios BAFTA: Mejor película y actor (Ejiofor). 10 nominaciones\r\n2013: Critics Choice: Mejor película, guión adaptado y actriz sec. 13 nomin.\r\n2013: Festival de Toronto: Mejor película (Premio del público)\r\n2013: National Board of Review (NBR): Mejores 10 películas del año\r\n2013: American Film Institute: Top 10 - Mejores películas del año\r\n2013: Premios David di Donatello: Nominada a mejor film extranjero\r\n2013: Círculo de Críticos de Nueva York: Mejor director. 5 nominaciones\r\n2013: Asociación de Críticos de Los Angeles: Mejor actriz sec. (Nyong\'o)\r\n2013: Premios Gotham: 3 nominaciones, incluyendo Mejor película\r\n2013: Premios Independent Spirit: 5 premios, incluyendo Mejor película. 7 nominaciones\r\n2013: Satellite Awards: Mejor película y mejor director. 10 nominaciones\r\n2013: Premios Guldbagge: Nominada a Mejor película extranjera\r\n2013: Sindicato de Productores (PGA): Mejor película\r\n2013: Sindicato de Directores (DGA): Nominada a Mejor director\r\n2013: Sindicato de Actores (SAG): Mejor actriz secundaria (Lupita Nyong\'o). 4 Nom\r\n2013: 5 premios Asociación de Críticos de Chicago, incluyendo mejor película. 11 nom.\r\n2014: Premios César: Nominada a Mejor film extranjero'),
(47, 'Bohemian Rhapsody', 'Reino Unido', 'Bryan Singer', 'Drama', 7.3, '2018: 4 Premios Oscar: incluyendo mejor actor (Malek), montaje y sonido. 5 nom.\r\n2018: Globos de Oro: Mejor película drama y actor (Rami Malek)\r\n2018: 2 Premios BAFTA: Mejor actor (Rami Malek) y sonido. 7 nominacoines\r\n2018: Critics Choice Awards: Nominada a mejor actor, vestuario y maquillaje\r\n2018: Asociación de Críticos de Chicago: Nominada a Mejor actor (Rami Malek)\r\n2018: Satellite Awards: Nominada a mejor actor comedia/musical (Rami Malek)\r\n2018: Sindicato de Productores (PGA): Nominada a mejor película\r\n2018: Sindicato de Actores (SAG): Mejor actor (Rami Malek). Nominada mejor cast\r\n2018: Premios David di Donatello: Nominada a Mejor film extranjero');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `usuarios`
--

CREATE TABLE `usuarios` (
  `id` int(100) NOT NULL,
  `nombre` varchar(500) COLLATE utf8_spanish_ci NOT NULL,
  `nombre usuario` varchar(50) COLLATE utf8_spanish_ci NOT NULL,
  `contraseña` varchar(50) COLLATE utf8_spanish_ci NOT NULL,
  `email` varchar(100) COLLATE utf8_spanish_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

--
-- Volcado de datos para la tabla `usuarios`
--

INSERT INTO `usuarios` (`id`, `nombre`, `nombre usuario`, `contraseña`, `email`) VALUES
(1, 'Adrián Diez', 'adri', 'epa', 'adri@kjsbfgjn.yee');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `películas`
--
ALTER TABLE `películas`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `usuarios`
--
ALTER TABLE `usuarios`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `películas`
--
ALTER TABLE `películas`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=48;

--
-- AUTO_INCREMENT de la tabla `usuarios`
--
ALTER TABLE `usuarios`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
